version: '3'

services:
  web:
    build: .
    command: sh -c "
      pytest test/ &&      
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env.docker

volumes:
  postgres_data: