"""fix unic=true

Revision ID: 0fda98b5d30d
Revises: 364887009559
Create Date: 2024-08-25 22:42:14.107837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0fda98b5d30d'
down_revision: Union[str, None] = '364887009559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__bet__game_id', 'bet', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq__bet__game_id', 'bet', ['game_id'])
    # ### end Alembic commands ###
