"""User Model

Revision ID: 364887009559
Revises: ba7b347fbcf8
Create Date: 2024-08-25 02:18:44.008162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364887009559'
down_revision: Union[str, None] = 'ba7b347fbcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__bet__id'), 'bet', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__bet__id'), 'bet', type_='unique')
    # ### end Alembic commands ###
