"""Game Model

Revision ID: 5c510b882eae
Revises: 
Create Date: 2024-08-24 22:34:46.189104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5c510b882eae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_player', sa.String(), nullable=False),
                    sa.Column('second_player', sa.String(), nullable=False),
                    sa.Column('first_player_result', sa.Enum('WIN', 'LOSE', 'NOT', name='gameenum'), nullable=False),
                    sa.Column('game_over', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__game')),
                    sa.UniqueConstraint('id', name=op.f('uq__game__id'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
