"""User Model

Revision ID: 79a62978bf2c
Revises: 5c510b882eae
Create Date: 2024-08-25 00:23:19.399068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '79a62978bf2c'
down_revision: Union[str, None] = '5c510b882eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_name', sa.String(), nullable=False),
                    sa.Column('balance', sa.Integer(), nullable=False),
                    sa.Column('frozen_balance', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__user')),
                    sa.UniqueConstraint('id', name=op.f('uq__user__id')),
                    sa.UniqueConstraint('user_name', name=op.f('uq__user__user_name'))
                    )
    op.create_unique_constraint(op.f('uq__game__id'), 'game', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__game__id'), 'game', type_='unique')
    op.drop_table('user')
    # ### end Alembic commands ###
