"""User Model add decimal

Revision ID: a82b24bf65a2
Revises: 79a62978bf2c
Create Date: 2024-08-25 00:31:27.250692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a82b24bf65a2'
down_revision: Union[str, None] = '79a62978bf2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
                    existing_type=sa.INTEGER(),
                    type_=sa.DECIMAL(precision=10, scale=2),
                    existing_nullable=False)
    op.alter_column('user', 'frozen_balance',
                    existing_type=sa.INTEGER(),
                    type_=sa.DECIMAL(precision=10, scale=2),
                    existing_nullable=False)
    op.create_unique_constraint(op.f('uq__user__id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__user__id'), 'user', type_='unique')
    op.alter_column('user', 'frozen_balance',
                    existing_type=sa.DECIMAL(precision=10, scale=2),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('user', 'balance',
                    existing_type=sa.DECIMAL(precision=10, scale=2),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###
