"""Game Model

Revision ID: ba7b347fbcf8
Revises: a82b24bf65a2
Create Date: 2024-08-25 01:44:05.483146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ba7b347fbcf8'
down_revision: Union[str, None] = 'a82b24bf65a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('bet_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('win_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('game_finished', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk__bet__game_id__game')),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__bet__user_id__user')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__bet')),
                    sa.UniqueConstraint('game_id', name=op.f('uq__bet__game_id')),
                    sa.UniqueConstraint('id', name=op.f('uq__bet__id'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    # ### end Alembic commands ###
